---
driver                 :
    name               : localhost

provisioner:
    name               : ansible_push
    verbose            : "vvvv"
    ansible_config     : "test/ansible.cfg"
    idempotency_test   : True

platforms:
    - name: travis

suites:
  - name            : empty
    provisioner     :
        playbook    : "test/application/empty.yml"
        extra_vars  : { 'kitchen_connection': 'smart' }