---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl git python-pip ruby ruby-dev build-essential autoconf
  - gem install bundler

install:
  - sudo pip install ansible
  - sudo apt-get install virtualbox vagrant
  - ruby --version
  - gem install mixlib-shellout -v '2.1.0'

script:
    - ansible --version
    - bundle install
    - KITCHEN_YAML=.kitchen_travis.yml bundle exec kitchen test travis


after_success:
    - echo "Success"